[workspace]
resolver = "2"
members = ["guests", "host", "lib", "primitives", "testing/ef-tests"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3

[workspace.dependencies]
bonsai-sdk = { version = "0.7.0", features = ["async"] }
hashbrown = { version = "0.14.3", features = ["inline-more"] }
risc0-build = { version = "0.21.0" }
risc0-zkvm = { version = "0.21.0", default-features = false }
revm-primitives = { version = "3.1", default_features = false }
revm = { version = "7.2", default-features = false, features = [
    "std",
    "serde",
    "optimism",
] }
